---
# handlers file for kiosk_mode
- name: Reboot
  ansible.builtin.reboot:
  when: kiosk_reboot | bool

- name: Restart GDM
  ansible.builtin.systemd:
    name: gdm
    state: restarted
  when: kiosk_reboot | bool
