---
- name: Get dynamic inventory
  hosts: localhost
  become: false
  gather_facts: false
  vars:
    inventory_namespace: edge-gitops-vms
    inventory_kind: Service
    inventory_target_group: VMs
    inventory_label_selectors:
      - edge-gitops-role=kiosk

  tasks:
    - name: Get {{ inventory_kind }}
      kubernetes.core.k8s_info:
        api_version: v1
        kind: "{{ inventory_kind }}"
        namespace: "{{ inventory_namespace }}"
        label_selectors: "{{ inventory_label_selectors }}"
      register: nodes

    - name: Add hosts
      ansible.builtin.add_host:
        hostname: "{{ item }}.{{ inventory_namespace }}.svc"
        groups:
          - "{{ inventory_target_group }}"
      loop: "{{ nodes | community.general.json_query('resources[*].metadata.name') }}"

    - name: Debug Nodelist
      ansible.builtin.debug:
        var: groups
